name: Security analysis
on:
  workflow_dispatch:
    inputs:
      # Tools to use
      ## Slither
      slither:
        description: "Enable Slither analysis"
        type: boolean
        default: true
      template-ref:
        required: false
        type: string
        default: "feat/sc-analysis"
        description: "template branch ref"

jobs:
  build-and-test:
    uses: aragon/github-templates/.github/workflows/sc-security-analysis.yml@${{inputs.template-ref}}
    with:
      slither: ${{ inputs.slither}}
      template-ref: ${{ inputs.template-ref }}


      #  notify:
#    needs: [build-and-test, deploy]
#    if: always()
#    runs-on: ubuntu-latest
#    steps:
#      - name: Notify teams
#        run: |
#          echo "Pipeline completed!"
#          echo "Build status: ${{ needs.build-and-test.result }}"
#          echo "Deploy status: ${{ needs.deploy.result }}"
#          if [ "${{ needs.deploy.result }}" = "success" ]; then
#            echo "Application URL: ${{ needs.deploy.outputs.deployment-url }}"
#          fi