name: Tests

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'deploy/**'
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  test-upgrades:
    strategy:
      fail-fast: true
    name: Test upgrades
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: oven-sh/setup-bun@v2

      - name: foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1.3.1

      - name: Show Forge version
        run: forge --version

      - name: Build
        run: bun run build-all

      - name: Run tests
        run: bun run test-upgrades
  test-fork:
    strategy:
      fail-fast: true
    name: Test fork
    runs-on: ubuntu-latest
    env:
      NETWORK: "sepolia"
      FORK_TEST_MODE: "new-factory"
      DEPLOY_AS_PRODUCTION: false
      TOKEN_TEST_WHALE: "0x"
      FACTORY_ADDRESS: "0x"
      MULTISIG_MEMBERS_JSON_FILE_NAME: "/script/multisig-members.json"
      MIN_APPROVALS: 1
      MULTISIG_PROPOSAL_EXPIRATION_PERIOD: "864000"
      MINT_TEST_TOKENS: true
      TOKEN1_ADDRESS: "0x0000000000000000000000000000000000000000"
      VE_TOKEN1_NAME: "Voting Escrow Token 1"
      VE_TOKEN1_SYMBOL: "veTK1"
      TOKEN2_ADDRESS: "0x0000000000000000000000000000000000000000"
      VE_TOKEN2_NAME: "Voting Escrow Token 2"
      VE_TOKEN2_SYMBOL: "veTK2"
      FEE_PERCENT: "0" # 10_000 = 100%
      WARMUP_PERIOD: "259200" # 3 days
      COOLDOWN_PERIOD: "259200" # 3 days
      MIN_LOCK_DURATION: "1"
      VOTING_PAUSED: true
      MIN_DEPOSIT: "10000000000000000" # 0.01 ETH
      MULTISIG_PLUGIN_REPO_ADDRESS: "0x9e7956C8758470dE159481e5DD0d08F8B59217A2"
      MULTISIG_PLUGIN_RELEASE: "1"
      MULTISIG_PLUGIN_BUILD: "2"
      SIMPLE_GAUGE_VOTER_REPO_ENS_SUBDOMAIN: "gauge-voter-${{ vars.GITHUB_RUN_ID }}"
      DAO_FACTORY: "0x7a62da7B56fB3bfCdF70E900787010Bc4c9Ca42e"
      PLUGIN_SETUP_PROCESSOR: "0xC24188a73dc09aA7C721f96Ad8857B469C01dC9f"
      PLUGIN_REPO_FACTORY: "0x07f49c49Ce2A99CF7C28F66673d406386BDD8Ff4"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: oven-sh/setup-bun@v2

      - name: foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1.3.1

      - name: Show Forge version
        run: forge --version

      - name: Build
        run: bun run build

      - name: Run tests
        run: bun run test-fork
  test-unit:
    strategy:
      fail-fast: true
    name: Test unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: oven-sh/setup-bun@v2

      - name: foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1.3.1

      - name: Show Forge version
        run: forge --version

      - name: Build
        run: bun run build

      - name: Run tests
        run: bun run test-unit
  